### ISSUE TITLE
Sidebar never updates

### ISSUE THREAD

**Issue by drinfernoo** [galloween/custom-sidebar-v2#3]
This component seems to be causing me nothing but trouble...

The only way I can get the sidebar to update when I make changes in `sidebar-order.json` is in Incognito Mode (I use Chrome). I've tried clearing data for that site, force refreshing, etc... And it seems that if I'm ever able to get it to update, it's only in Incognito.

My `sidebar-order.json` here: https://pastebin.com/fcqXhmgD

Is there any particular reason why this one doesn't seem to want to update for me?

**Comment by galloween** [comment]
@drinfernoo 
Sorry to hear that! Im also using Chrome and "empty cash and hard reload" usually works for me. 
I made some adjustments, can you try to update/redownload the plugin and see if it helps.
Also, check the console - there might be some errors. Also the version in the log from the plugin - make sure it is the latest (301217_2359). 
There will also be an object with some data that may help you figure out the problem - you will be able to see if it actually gets your config file or not... 
Let me know if this helps!

<table><tr><td>
<img src="https://user-images.githubusercontent.com/2077754/146614332-6bf67f9b-f910-46a6-b8a2-9dff71f2eb57.png">
</td><td>
<img src="https://user-images.githubusercontent.com/2077754/146614355-a323819d-a336-4aac-a057-d8c83161e236.png">
</td></tr></table>
<img width="449" alt="CleanShot 2021-12-18 at 00 22 33@2x" src="https://user-images.githubusercontent.com/2077754/146614782-22b330cf-2cdd-4969-a3f4-bfe8b7e024bc.png">

**Comment by drinfernoo** [comment]
I'll give it a try in a while... I don't have the option to "Empty Cache and Hard Reload", but Ctrl+F5 has always worked for me with other Lovelace resources.

**Comment by galloween** [comment]
ah, always forget to mention that "clear cache and hard-refresh" menu appears 
if you right-click on the refresh button **while Dev Tools panel is open**(F12)

**Comment by drinfernoo** [comment]
This seems to be working now 👍 Will let you know if I have any more issues.
