### ISSUE TITLE
Icons not showing for new_item

### ISSUE THREAD

**Issue by silviudc** [galloween/custom-sidebar-v2#8]
I have this configured in my sidebar-order.json

`    {
      "new_item": true,
      "item": "OpenEVSE",
      "href": "http://192.168.0.77",
      "icon:": "mdi:car-electric",
      "order": 8
    }`

And it is not showing the icon, I have tried clearing the browser cache, reboot HA, etc and the same.
![image](https://user-images.githubusercontent.com/17740184/154683374-954d0690-b988-469c-acbf-9e7d8ea33298.png)

Also is there a way to have the new_item objects open up in a new browser window?

**Comment by galloween** [comment]
> Also is there a way to have the new_item objects open up in a new browser window?

yes, add `"target": "_blank"`

**Comment by galloween** [comment]
you also may be able to open your link in an iframe, see here: https://github.com/galloween/custom-sidebar-v2#combine-with-iframe-panel-to-show-external-content-inside-home-assitant

it does not always work, though

**Comment by silviudc** [comment]
Thanks for the suggest, the iframe works fine and the icon is showing also this way :)
